spring:
  application:
    name: Hotel-Backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/hotel_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: gallagher
    password: gallagher09
  
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework: DEBUG

server:
  port: 8104

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # un jour
      refresh-token:
        expiration: 604800000 # 7 jours